# coding: utf-8

"""
    easybill REST API

     The first version of the easybill REST API. [CHANGELOG](https://api.easybill.de/rest/v1/CHANGELOG.md)  ## Authentication  You can choose between two available methods: `Basic Auth` or `Bearer Token`.  In each HTTP request, one of the following HTTP headers is required:  ``` # Basic Auth Authorization: Basic base64_encode('<email>:<api_key>') # Bearer Token Authorization: Bearer <api_key> ```  ## Limitations  ### Request Limit  * PLUS: 10 requests per minute * BUSINESS: 60 requests per minute  If the limit is exceeded, you will receive the HTTP error: `429 Too Many Requests`  ### Result Limit  All result lists are limited to 100 by default. This limit can be increased by the query parameter `limit` to a maximum of 1000.  ## Query filter  Many list resources can be filtered. In `/documents` you can filter e.g. by number with `/documents?number=111028654`. If you want to filter multiple numbers, you can either enter them separated by commas `/documents?number=111028654,222006895` or as an array `/documents?number[]=111028654&number[]=222006895`.  **Warning**: The maximum size of an HTTP request line in bytes is 4094. If this limit is exceeded, you will receive the HTTP error: `414 Request-URI Too Large`  ### Escape commas in query  You can escape commans in query `name=Patrick\\, Peter` if you submit the header `X-Easybill-Escape: true` in your request.  ## Property login_id  This is the login of your admin or employee account.  ## Date and Date-Time format Please use the timezone `Europe/Berlin`. * **date** = *Y-m-d* = `2016-12-31` * **date-time** = *Y-m-d H:i:s* = `2016-12-31 03:13:37`  Date or datetime can be `null` because the attributes have been added later and the entry is older.  # noqa: E501

    The version of the OpenAPI document: 1.48.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.customers import Customers  # noqa: E501
from openapi_client.rest import ApiException

class TestCustomers(unittest.TestCase):
    """Customers unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Customers
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.customers.Customers()  # noqa: E501
        if include_optional :
            return Customers(
                items = [
                    openapi_client.models.customer.Customer(
                        acquire_options = 56, 
                        additional_groups_ids = [], 
                        bank_account = '0', 
                        bank_account_owner = '0', 
                        bank_bic = '0', 
                        bank_code = '0', 
                        bank_iban = '0', 
                        bank_name = '0', 
                        birth_date = 'Sat Dec 31 01:00:00 CET 2016', 
                        cash_allowance = 0, 
                        cash_allowance_days = 7, 
                        cash_discount = 1.337, 
                        cash_discount_type = 'PERCENT', 
                        city = 'Kaarst', 
                        company_name = 'easybill GmbH', 
                        country = 'DE', 
                        created_at = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        updated_at = '0', 
                        delivery_city = '0', 
                        delivery_company_name = '0', 
                        delivery_country = '0', 
                        delivery_first_name = '0', 
                        delivery_last_name = '0', 
                        delivery_personal = False, 
                        delivery_salutation = 56, 
                        delivery_street = '0', 
                        delivery_suffix_1 = '0', 
                        delivery_suffix_2 = '0', 
                        delivery_zip_code = '0', 
                        display_name = '0', 
                        emails = [max.mustermann@easybill.de], 
                        fax = '+49 2154 89701 29', 
                        first_name = 'Max', 
                        grace_period = 56, 
                        due_in_days = 56, 
                        group_id = 56, 
                        id = 56, 
                        info_1 = '0', 
                        info_2 = '0', 
                        internet = 'https://www.easybill.de', 
                        last_name = 'Mustermann', 
                        login_id = 56, 
                        mobile = '0', 
                        note = '0', 
                        number = '0', 
                        payment_options = 56, 
                        personal = False, 
                        phone_1 = '+49 2154 89701 20', 
                        phone_2 = '0', 
                        postbox = '0', 
                        postbox_city = '0', 
                        postbox_country = '0', 
                        postbox_zip_code = '0', 
                        sale_price_level = 'SALEPRICE2', 
                        salutation = 56, 
                        sepa_agreement = 'BASIC', 
                        sepa_agreement_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        sepa_mandate_reference = '0', 
                        since_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        street = 'Düsselstr. 21', 
                        suffix_1 = '0', 
                        suffix_2 = '0', 
                        tax_number = '0', 
                        court = 'Berlin', 
                        court_registry_number = 'HRB XXXXX X', 
                        tax_options = 'nStb', 
                        title = '0', 
                        vat_identifier = 'DE814878557', 
                        zip_code = '41564', )
                    ]
            )
        else :
            return Customers(
        )

    def testCustomers(self):
        """Test Customers"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
