# coding: utf-8

"""
    easybill REST API

     The first version of the easybill REST API. [CHANGELOG](https://api.easybill.de/rest/v1/CHANGELOG.md)  ## Authentication  You can choose between two available methods: `Basic Auth` or `Bearer Token`.  In each HTTP request, one of the following HTTP headers is required:  ``` # Basic Auth Authorization: Basic base64_encode('<email>:<api_key>') # Bearer Token Authorization: Bearer <api_key> ```  ## Limitations  ### Request Limit  * PLUS: 10 requests per minute * BUSINESS: 60 requests per minute  If the limit is exceeded, you will receive the HTTP error: `429 Too Many Requests`  ### Result Limit  All result lists are limited to 100 by default. This limit can be increased by the query parameter `limit` to a maximum of 1000.  ## Query filter  Many list resources can be filtered. In `/documents` you can filter e.g. by number with `/documents?number=111028654`. If you want to filter multiple numbers, you can either enter them separated by commas `/documents?number=111028654,222006895` or as an array `/documents?number[]=111028654&number[]=222006895`.  **Warning**: The maximum size of an HTTP request line in bytes is 4094. If this limit is exceeded, you will receive the HTTP error: `414 Request-URI Too Large`  ### Escape commas in query  You can escape commans in query `name=Patrick\\, Peter` if you submit the header `X-Easybill-Escape: true` in your request.  ## Property login_id  This is the login of your admin or employee account.  ## Date and Date-Time format Please use the timezone `Europe/Berlin`. * **date** = *Y-m-d* = `2016-12-31` * **date-time** = *Y-m-d H:i:s* = `2016-12-31 03:13:37`  Date or datetime can be `null` because the attributes have been added later and the entry is older.  # noqa: E501

    The version of the OpenAPI document: 1.48.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class Login(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'first_name': 'str',
        'last_name': 'str',
        'display_name': 'str',
        'phone': 'str',
        'email': 'str',
        'email_signature': 'str',
        'login_type': 'str'
    }

    attribute_map = {
        'id': 'id',
        'first_name': 'first_name',
        'last_name': 'last_name',
        'display_name': 'display_name',
        'phone': 'phone',
        'email': 'email',
        'email_signature': 'email_signature',
        'login_type': 'login_type'
    }

    def __init__(self, id=None, first_name=None, last_name=None, display_name=None, phone=None, email=None, email_signature=None, login_type='ASSISTANT', local_vars_configuration=None):  # noqa: E501
        """Login - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._first_name = None
        self._last_name = None
        self._display_name = None
        self._phone = None
        self._email = None
        self._email_signature = None
        self._login_type = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if first_name is not None:
            self.first_name = first_name
        if last_name is not None:
            self.last_name = last_name
        if display_name is not None:
            self.display_name = display_name
        if phone is not None:
            self.phone = phone
        if email is not None:
            self.email = email
        if email_signature is not None:
            self.email_signature = email_signature
        if login_type is not None:
            self.login_type = login_type

    @property
    def id(self):
        """Gets the id of this Login.  # noqa: E501


        :return: The id of this Login.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Login.


        :param id: The id of this Login.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def first_name(self):
        """Gets the first_name of this Login.  # noqa: E501


        :return: The first_name of this Login.  # noqa: E501
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this Login.


        :param first_name: The first_name of this Login.  # noqa: E501
        :type: str
        """

        self._first_name = first_name

    @property
    def last_name(self):
        """Gets the last_name of this Login.  # noqa: E501


        :return: The last_name of this Login.  # noqa: E501
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this Login.


        :param last_name: The last_name of this Login.  # noqa: E501
        :type: str
        """

        self._last_name = last_name

    @property
    def display_name(self):
        """Gets the display_name of this Login.  # noqa: E501


        :return: The display_name of this Login.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this Login.


        :param display_name: The display_name of this Login.  # noqa: E501
        :type: str
        """

        self._display_name = display_name

    @property
    def phone(self):
        """Gets the phone of this Login.  # noqa: E501


        :return: The phone of this Login.  # noqa: E501
        :rtype: str
        """
        return self._phone

    @phone.setter
    def phone(self, phone):
        """Sets the phone of this Login.


        :param phone: The phone of this Login.  # noqa: E501
        :type: str
        """

        self._phone = phone

    @property
    def email(self):
        """Gets the email of this Login.  # noqa: E501


        :return: The email of this Login.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this Login.


        :param email: The email of this Login.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def email_signature(self):
        """Gets the email_signature of this Login.  # noqa: E501


        :return: The email_signature of this Login.  # noqa: E501
        :rtype: str
        """
        return self._email_signature

    @email_signature.setter
    def email_signature(self, email_signature):
        """Sets the email_signature of this Login.


        :param email_signature: The email_signature of this Login.  # noqa: E501
        :type: str
        """

        self._email_signature = email_signature

    @property
    def login_type(self):
        """Gets the login_type of this Login.  # noqa: E501


        :return: The login_type of this Login.  # noqa: E501
        :rtype: str
        """
        return self._login_type

    @login_type.setter
    def login_type(self, login_type):
        """Sets the login_type of this Login.


        :param login_type: The login_type of this Login.  # noqa: E501
        :type: str
        """
        allowed_values = ["ADMIN", "ASSISTANT"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and login_type not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `login_type` ({0}), must be one of {1}"  # noqa: E501
                .format(login_type, allowed_values)
            )

        self._login_type = login_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Login):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Login):
            return True

        return self.to_dict() != other.to_dict()
