# coding: utf-8

"""
    easybill REST API

     The first version of the easybill REST API. [CHANGELOG](https://api.easybill.de/rest/v1/CHANGELOG.md)  ## Authentication  You can choose between two available methods: `Basic Auth` or `Bearer Token`.  In each HTTP request, one of the following HTTP headers is required:  ``` # Basic Auth Authorization: Basic base64_encode('<email>:<api_key>') # Bearer Token Authorization: Bearer <api_key> ```  ## Limitations  ### Request Limit  * PLUS: 10 requests per minute * BUSINESS: 60 requests per minute  If the limit is exceeded, you will receive the HTTP error: `429 Too Many Requests`  ### Result Limit  All result lists are limited to 100 by default. This limit can be increased by the query parameter `limit` to a maximum of 1000.  ## Query filter  Many list resources can be filtered. In `/documents` you can filter e.g. by number with `/documents?number=111028654`. If you want to filter multiple numbers, you can either enter them separated by commas `/documents?number=111028654,222006895` or as an array `/documents?number[]=111028654&number[]=222006895`.  **Warning**: The maximum size of an HTTP request line in bytes is 4094. If this limit is exceeded, you will receive the HTTP error: `414 Request-URI Too Large`  ### Escape commas in query  You can escape commans in query `name=Patrick\\, Peter` if you submit the header `X-Easybill-Escape: true` in your request.  ## Property login_id  This is the login of your admin or employee account.  ## Date and Date-Time format Please use the timezone `Europe/Berlin`. * **date** = *Y-m-d* = `2016-12-31` * **date-time** = *Y-m-d H:i:s* = `2016-12-31 03:13:37`  Date or datetime can be `null` because the attributes have been added later and the entry is older.  # noqa: E501

    The version of the OpenAPI document: 1.48.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class PostBox(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'document_id': 'int',
        'to': 'str',
        'cc': 'str',
        '_from': 'str',
        'subject': 'str',
        'message': 'str',
        'date': 'date',
        'created_at': 'datetime',
        'processed_at': 'datetime',
        'send_by_self': 'bool',
        'send_with_attachment': 'bool',
        'type': 'str',
        'status': 'str',
        'status_msg': 'str',
        'login_id': 'int'
    }

    attribute_map = {
        'id': 'id',
        'document_id': 'document_id',
        'to': 'to',
        'cc': 'cc',
        '_from': 'from',
        'subject': 'subject',
        'message': 'message',
        'date': 'date',
        'created_at': 'created_at',
        'processed_at': 'processed_at',
        'send_by_self': 'send_by_self',
        'send_with_attachment': 'send_with_attachment',
        'type': 'type',
        'status': 'status',
        'status_msg': 'status_msg',
        'login_id': 'login_id'
    }

    def __init__(self, id=None, document_id=None, to=None, cc=None, _from=None, subject=None, message=None, date=None, created_at=None, processed_at=None, send_by_self=None, send_with_attachment=None, type=None, status=None, status_msg=None, login_id=None, local_vars_configuration=None):  # noqa: E501
        """PostBox - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._document_id = None
        self._to = None
        self._cc = None
        self.__from = None
        self._subject = None
        self._message = None
        self._date = None
        self._created_at = None
        self._processed_at = None
        self._send_by_self = None
        self._send_with_attachment = None
        self._type = None
        self._status = None
        self._status_msg = None
        self._login_id = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if document_id is not None:
            self.document_id = document_id
        if to is not None:
            self.to = to
        if cc is not None:
            self.cc = cc
        if _from is not None:
            self._from = _from
        if subject is not None:
            self.subject = subject
        if message is not None:
            self.message = message
        if date is not None:
            self.date = date
        if created_at is not None:
            self.created_at = created_at
        if processed_at is not None:
            self.processed_at = processed_at
        if send_by_self is not None:
            self.send_by_self = send_by_self
        if send_with_attachment is not None:
            self.send_with_attachment = send_with_attachment
        if type is not None:
            self.type = type
        if status is not None:
            self.status = status
        if status_msg is not None:
            self.status_msg = status_msg
        if login_id is not None:
            self.login_id = login_id

    @property
    def id(self):
        """Gets the id of this PostBox.  # noqa: E501


        :return: The id of this PostBox.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this PostBox.


        :param id: The id of this PostBox.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def document_id(self):
        """Gets the document_id of this PostBox.  # noqa: E501


        :return: The document_id of this PostBox.  # noqa: E501
        :rtype: int
        """
        return self._document_id

    @document_id.setter
    def document_id(self, document_id):
        """Sets the document_id of this PostBox.


        :param document_id: The document_id of this PostBox.  # noqa: E501
        :type: int
        """

        self._document_id = document_id

    @property
    def to(self):
        """Gets the to of this PostBox.  # noqa: E501


        :return: The to of this PostBox.  # noqa: E501
        :rtype: str
        """
        return self._to

    @to.setter
    def to(self, to):
        """Sets the to of this PostBox.


        :param to: The to of this PostBox.  # noqa: E501
        :type: str
        """

        self._to = to

    @property
    def cc(self):
        """Gets the cc of this PostBox.  # noqa: E501


        :return: The cc of this PostBox.  # noqa: E501
        :rtype: str
        """
        return self._cc

    @cc.setter
    def cc(self, cc):
        """Sets the cc of this PostBox.


        :param cc: The cc of this PostBox.  # noqa: E501
        :type: str
        """

        self._cc = cc

    @property
    def _from(self):
        """Gets the _from of this PostBox.  # noqa: E501


        :return: The _from of this PostBox.  # noqa: E501
        :rtype: str
        """
        return self.__from

    @_from.setter
    def _from(self, _from):
        """Sets the _from of this PostBox.


        :param _from: The _from of this PostBox.  # noqa: E501
        :type: str
        """

        self.__from = _from

    @property
    def subject(self):
        """Gets the subject of this PostBox.  # noqa: E501


        :return: The subject of this PostBox.  # noqa: E501
        :rtype: str
        """
        return self._subject

    @subject.setter
    def subject(self, subject):
        """Sets the subject of this PostBox.


        :param subject: The subject of this PostBox.  # noqa: E501
        :type: str
        """

        self._subject = subject

    @property
    def message(self):
        """Gets the message of this PostBox.  # noqa: E501


        :return: The message of this PostBox.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this PostBox.


        :param message: The message of this PostBox.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def date(self):
        """Gets the date of this PostBox.  # noqa: E501


        :return: The date of this PostBox.  # noqa: E501
        :rtype: date
        """
        return self._date

    @date.setter
    def date(self, date):
        """Sets the date of this PostBox.


        :param date: The date of this PostBox.  # noqa: E501
        :type: date
        """

        self._date = date

    @property
    def created_at(self):
        """Gets the created_at of this PostBox.  # noqa: E501


        :return: The created_at of this PostBox.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this PostBox.


        :param created_at: The created_at of this PostBox.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def processed_at(self):
        """Gets the processed_at of this PostBox.  # noqa: E501


        :return: The processed_at of this PostBox.  # noqa: E501
        :rtype: datetime
        """
        return self._processed_at

    @processed_at.setter
    def processed_at(self, processed_at):
        """Sets the processed_at of this PostBox.


        :param processed_at: The processed_at of this PostBox.  # noqa: E501
        :type: datetime
        """

        self._processed_at = processed_at

    @property
    def send_by_self(self):
        """Gets the send_by_self of this PostBox.  # noqa: E501


        :return: The send_by_self of this PostBox.  # noqa: E501
        :rtype: bool
        """
        return self._send_by_self

    @send_by_self.setter
    def send_by_self(self, send_by_self):
        """Sets the send_by_self of this PostBox.


        :param send_by_self: The send_by_self of this PostBox.  # noqa: E501
        :type: bool
        """

        self._send_by_self = send_by_self

    @property
    def send_with_attachment(self):
        """Gets the send_with_attachment of this PostBox.  # noqa: E501


        :return: The send_with_attachment of this PostBox.  # noqa: E501
        :rtype: bool
        """
        return self._send_with_attachment

    @send_with_attachment.setter
    def send_with_attachment(self, send_with_attachment):
        """Sets the send_with_attachment of this PostBox.


        :param send_with_attachment: The send_with_attachment of this PostBox.  # noqa: E501
        :type: bool
        """

        self._send_with_attachment = send_with_attachment

    @property
    def type(self):
        """Gets the type of this PostBox.  # noqa: E501


        :return: The type of this PostBox.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this PostBox.


        :param type: The type of this PostBox.  # noqa: E501
        :type: str
        """
        allowed_values = ["FAX", "MAIL", "POST"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and type not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def status(self):
        """Gets the status of this PostBox.  # noqa: E501


        :return: The status of this PostBox.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this PostBox.


        :param status: The status of this PostBox.  # noqa: E501
        :type: str
        """
        allowed_values = ["WAITING", "PREPARE", "ERROR", "OK", "PROCESSING"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and status not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def status_msg(self):
        """Gets the status_msg of this PostBox.  # noqa: E501


        :return: The status_msg of this PostBox.  # noqa: E501
        :rtype: str
        """
        return self._status_msg

    @status_msg.setter
    def status_msg(self, status_msg):
        """Sets the status_msg of this PostBox.


        :param status_msg: The status_msg of this PostBox.  # noqa: E501
        :type: str
        """

        self._status_msg = status_msg

    @property
    def login_id(self):
        """Gets the login_id of this PostBox.  # noqa: E501


        :return: The login_id of this PostBox.  # noqa: E501
        :rtype: int
        """
        return self._login_id

    @login_id.setter
    def login_id(self, login_id):
        """Sets the login_id of this PostBox.


        :param login_id: The login_id of this PostBox.  # noqa: E501
        :type: int
        """

        self._login_id = login_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PostBox):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PostBox):
            return True

        return self.to_dict() != other.to_dict()
